#!/usr/bin/env sh

externals/pictorial/pictorial.rb --overwrite-existing-file --from-directory "design" --to-directory "frontend/ui/arboreal.images" --rename-from "okogreen.scaffold_(arboreal.+).png$" --rename-to "\\1.png"




